# Generated by Django 5.0.4 on 2024-04-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_entorno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltaje', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('cargadores', models.ManyToManyField(to='laptops.laptop')),
            ],
        ),
    ]
