# Generated by Django 5.0.4 on 2024-04-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_cargador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(max_length=100)),
                ('ofis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laptops.laptop')),
            ],
        ),
    ]
