# Generated by Django 5.0.4 on 2024-04-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0004_oficina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
