# Generated by Django 5.0.4 on 2024-04-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nucleos', models.IntegerField()),
                ('marca', models.CharField(max_length=100)),
                ('sistema', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('rom', models.CharField(max_length=100)),
            ],
        ),
    ]
